import { Providers } from '@/common';
import { RootLayout as ViewportLayout } from '@sambad/web-domains/commmon';
import dayjs from 'dayjs';
import localFont from 'next/font/local';

import type { Metadata } from 'next';

dayjs.locale('ko');

const pretendard = localFont({
  src: '../public/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <Providers>
          <ViewportLayout>{children}</ViewportLayout>
        </Providers>
      </body>
    </html>
  );
}
