#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git symbolic-ref --short HEAD)
changed_files=$(git diff --name-only origin/$current_branch)

if echo "$changed_files" | grep -E 'package\.json|packages/*/package\.json|apps/*/package\.json|pnpm-workspace\.yaml|pnpm-lock\.yaml' > /dev/null 2>&1; then
  echo "패키지 파일 변경 사항이 감지되었습니다. pnpm install을 실행합니다."
  pnpm install
else
  echo "패키지 파일 변경 사항이 없습니다."
fi