reviewers:
  - githubName: Doeunnkimm
    slackId: U07600UQG3T
    name: WEB_김도은
  - githubName: semnil5202
    slackId: U075KR29RGR
    name: Web_이세민
  - githubName: LeeJeongHooo
    slackId: U075C1A16LT
    name: Web_이정호
  - githubName: Andrevile
    slackId: U07545VMS21
    name: Web_장종오
